### ISSUE TITLE
Estudio posicionamiento SEO

### ISSUE THREAD

**Issue by juaneguren** [juaneguren/FLORISTERIA#17]
La optimización para motores de búsqueda o [SEO] (Search Engine Optimization)

**Comment by juaneguren** [comment]
https://javiercallejo.net/cuanto-cuesta-salir-primero-en-google/
https://javiercallejo.net/crear-campanas-de-publicidad-en-instagram/

**Comment by ghost** [comment]
https://nonstop-femur-026.notion.site/GOOGLE-ADS-Como-publicitar-nuestra-tienda-en-google-en-proceso-ca01c30e15c248a5b15ee30454a5bc62
